project_id = "ujaefswhljrekcwesqyy"

[functions.admin-reset-password]
verify_jwt = true

[functions.toggle-user-status]
verify_jwt = true

[functions.check-high-priority]
verify_jwt = true

[functions.daily-gemini-analyze]
verify_jwt = true

[functions.send-notification]
verify_jwt = true
